### PR TITLE
fix meta.tmpl code generating incomplete issue when mixins field has validators

### PR DESCRIPTION
**Pull request by kidlj**
In meta.tmpl, there is an issue when mixins field has validators, the generated code is incomplete.

mixins_validator

The screenshot shows the generated code taking the [official mixins demo code](https://entgo.io/docs/schema-mixin/) as an example.

This pull request is a fix.

### CODE REVIEW

**Comment by kidlj** [comment]
I don't know if I should regenerate bindata.go, but without doing this the modified meta.tmpl won't take effect.

**Comment by a8m** [comment]
Hey, thanks for your contribution @kidlj!

> I don't know if I should regenerate bindata.go, but without doing this the modified meta.tmpl won't take effect.

Yes. You should run `go generate ./...` from the root of the project.

**Comment by kidlj** [comment]
But I'm seeing a `entc/gen/internal/bindata.go` conflict, don't know why.

**Comment by a8m** [comment]
> But I'm seeing a entc/gen/internal/bindata.go conflict, don't know why.

Not sure why either.  Are you rebased on `master`?

**Comment by kidlj** [comment]
Don't know how but my fork of this repository is in a situation that `master` is even with here, but the patch branch is 58 commits behind `master`. I must have made a mistake.

So this pull request is kind of messed up. I'm closing it and open a new one, with clean commits ahead of `master`.

**Pull request closed without merging**
