### PR TITLE
use strconv.FormatInt for string id

### PR DESCRIPTION
**Pull request by stevenferrer**
Use `strconv.FormatInt` instead of type casting string ID

### CODE REVIEW

**Comment by a8m** [comment]
Hey @stevenferrer and thanks for your contribution. 

Can you give more context for this PR? I assume it's related to previous functionality mentioned here - https://github.com/facebookincubator/ent/issues/127#issuecomment-583834177

**Comment by stevenferrer** [comment]
Hi @a8m, likewise, thank you very much for this amazing project!

I just want to address a small issue when using `--idtype string` specifically a line generated in [`assignValues`](https://github.com/stevenferrer/ent-demo/blob/master/ent/user.go#L40) and [`[Entity]Create.sqlSave`](https://github.com/stevenferrer/ent-demo/blob/master/ent/user_create.go#L83).

The difference demonstrated below:

Current: `fmt.Printf("%#v", string(1))` produces `"\x01"`
Proposed: `fmt.Printf("%#v", strconv.FormatInt(1, 10)` produces `"1"`

I'm not sure though if #127 is related.

**Comment by a8m** [comment]
Can you elaborate how do you use `string` id-type with SQL? IDs are stored as int in the database? If yes, what's the reason for this?

As mentioned in the linked comment:

> This (legacy) option was added to allow using the same generate ent package for both AWS Neptune (gremlin) and SQL dialects. Neptune uses UUID strings for its IDs, and MySQL is configured with numeric types for its PKs (in our deployment). Therefore, **the type in the code must be string, and we convert it to int before/after the data were loaded.**

**Comment by stevenferrer** [comment]
An example is when you use `json.Marshal`:

```go
brown := client.User.Create().SetName("brown").SaveX(ctx)
b, _ := json.Marshal(brown)
fmt.Println(string(b))
```
Outputs:
```json
{"id":"\u0001","name":"brown"}
```

**Comment by a8m** [comment]
Thanks for sharing the example @stevenferrer. Can you please answer my previous comment to help me get more context?

> Can you elaborate how do you use string id-type with SQL? IDs are stored as int in the database? If yes, what's the reason for this?

**Comment by stevenferrer** [comment]
We're using `PostgreSQL` and before migrating some other parts of our system to ent, we're already using `bigserial` as our ID type and we're mapping it as `string` in our Go structs. 

For example, the below table:

```sql
CREATE TABLE address (
    id bigserial NOT NULL,
    unit_no varchar NOT NULL,
    barangay varchar NOT NULL,
    province varchar NOT NULL,
    city varchar NOT NULL,
    updated_at timestamp,
    created_at timestamp NOT NULL DEFAULT now()
);
```

is mapped to this struct:

```go
type Address struct {
	ID string `json:"id"`
	UnitNo string `json:"unitNo"`
	Barangay string `json:"barangay"`
	Province string `json:"province"`
	City string `json:"city"`
	UpdatedAt *time.Time `json:"-"`
	CreatedAt *time.Time `json:"createdAt"`
}
```

**Comment by a8m** [comment]
> We're using PostgreSQL and before migrating some other parts of our system to ent, we're already using bigserial as our ID type and we're mapping it as string in our Go structs.

Thanks for sharing this information. 

There's no way to auto-map numeric value to string type in ent. Your PR fixes one problem with this, but there are so many other places that need to be changed in order to support this.

The [GoType](https://entgo.io/docs/schema-fields/#go-type) option is used exactly for cases like this, but it doesn't support ID fields as the moment. Once I'll add the support for this, you will be able to use it as follows:

```go
type StringID string // Need to implement the schema/field.ValueScanner interface.

func (User) Fields() []ent.Field {
	return []ent.Field{
		field.Int("id").
			GoType(new(StringID)),
	}
}
```

If you don't want to be blocked on this, you can use [external-templates](https://entgo.io/docs/templates/) for now (to override the existing behavior) and update your code in the future.

**Comment by stevenferrer** [comment]
Ok, got it. Will probably use a workaround for now, thanks for the suggestion! Closing this PR then.

**Comment by a8m** [comment]
I'll update this PR with the new API soon @stevenferrer.
Thanks for your contribution :)

**Pull request closed without merging**
