### PR TITLE
proposal: empty slice instead of nil slice in sqlAll

### PR DESCRIPTION
**Pull request by aca**
When sqlAll fails to match any data, it returns nil slice (with no error).
But when marshaling nil slice to json, it returns 'null'
So, When you are writing json rest api which expects response in array. You have to do something like this.

```
func (s *server) ListOrganization(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	orgs, err := s.db.Organization.Query().All(ctx)
	if err != nil {
		render.Render(w, r, ErrServerError(r, err))
		return
	}
	if len(orgs) == 0 {
		render.JSON(w, r, []*ent.Organization{})
	}
	render.JSON(w, r, orgs)
}
```

It would be very helpful it sqlAll just returns empty slice instead of nil slice.

### CODE REVIEW

**Comment by aca** [comment]
I will check the test failure later.

**Comment by a8m** [comment]
LGTM! Please rebase and regenerate assets:
```
go generate ./entc/gen/...
go generate ./...
```

**Comment by aca** [comment]
@a8m rebased!

**Comment by aca** [comment]
hmm I will check the test

**Comment by aca** [comment]
fixed.

**Comment by a8m** [comment]
Thanks @aca!

**Pull request merged**
