### PR TITLE
wip: postgresql

### PR DESCRIPTION
**Pull request by cliedeman**
TODO:
- [ ] Handle enum creation
- [ ] Auto increment mapping (Postgres only has identity and serial)

Design
- [ ] Postgres Range type?
- [ ] Should more specialised date/time types be created?

### CODE REVIEW

**Comment by erka** [comment]
You could use `pg_isready` for healthcheck of postgres

**Comment by alexsn** [comment]
Thanks for the PR @cliedeman, please note that integration tests are failing and needs fixing.

**Comment by a8m** [comment]
Thanks for the PR @cliedeman, I'll review this after finishing and landing #84.

**Comment by cliedeman** [comment]
@alexsn This is as far as I got before getting stuck.

builder.go will need to be refactored to allow changing the quote character and how arguments are generated.

Some example code that needs to be changed

```
func (s *Selector) C(column string) string {
	if s.as != "" {
		return fmt.Sprintf("`%s`.`%s`", s.as, column)
	}
	return s.Table().C(column)
}

// Columns returns a list of formatted strings for a selected columns from this statement.
func (s *Selector) Columns(columns ...string) []string {
	var names []string
	for _, c := range columns {
		names = append(names, s.C(c))
	}
	return names
}
```

The identifier quoting needs to be deferred to later execution process. Ideally when Query is invoked probably. 

Arg is even more problematic because postgres requires numbered arguments. This means we need to track query variables and handle the nested query case

```
func (b *Builder) Arg(a interface{}) *Builder {
	switch a := a.(type) {
	case *raw:
		b.WriteString(a.s)
	default:
		b.WriteString("?")
		b.args = append(b.args, a)
	}
	return b
}
```

I have tried a few attempts to refactor it but nothing promising yet. My latest idea if to remove the buffer embed and replace all the WriteStrings with tokens or objects that can be converted to dialect specific sql later

Ciaran

**Comment by cliedeman** [comment]
Rebased on master. next hurdle is handling postgres enums. They need a separate sql statement to be emitted to create a user type.

Postgres also does not have a real auto increment type and the serial type [should be avoided](https://wiki.postgresql.org/wiki/Don't_Do_This#Don.27t_use_serial)

**Comment by a8m** [comment]
Hey @cliedeman, can you please split it into separated PRs? For example, `Column.Postgres` and `Column.ScanPostgres` should be in one PR, and so on.

BTW, we start to work on this as well, so it'll help us to push this feature faster.

**Comment by cliedeman** [comment]
@a8m I will probably only get to it this weekend.I don't mind if you roll the changes into another PR if you get to it before I do

**Comment by ajwerner** [comment]
Do you have any interest in not using postgres’s Reum type? SQLite doesn’t have them. 

I’m asking because I suspect that will be the only compatibility problem that would prevent this dialect from also working with CockroachDB.

**Comment by cliedeman** [comment]
It’s not on the roadmap to support cockroach but it should work if you just don’t use enums?

**Comment by ajwerner** [comment]
Cool, I’ll try it out after the Postgres support merges. Cockroach speaks Postgres wire protocol and the Postgres sql dialect but it doesn’t have 100% compatibility. Enumerated are a big one. Triggers are also not supported but there is a changefeed mechanism which can generally be used instead. I understand cockroach isn’t on the roadmap currently but I’m hopeful getting it to work after Postgres support merges should be a small amount of work which I’d be happy to try to tackle.

**Comment by a8m** [comment]
PostgreSQL support was added. Closing.

Thank you very much @cliedeman for your contribution! I really appreciate the time you invested in this PR, but I tried to use it and some of the major functionally didn't work for me.

@ajwerner, you are welcome to give it a try and let me know if that works for you. Thanks!

**Comment by cliedeman** [comment]
@a8m Not a problem Thanks, I am sure I will find something else to contribute.

**Comment by T-M-A** [comment]
> I understand cockroach isn’t on the roadmap currently but I’m hopeful getting it to work after Postgres support merges should be a small amount of work which I’d be happy to try to tackle.
Hello, 
have news with cockroach?

**Pull request closed without merging**
